vim:fileencoding=utf-8:foldmethod=marker

background_opacity 0.8
background_blur 25

# font
font_family        JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 18.0
disable_ligatures never

# hystory
scrollback_lines 100

# colorscheme
background              #171717
foreground              #737373
cursor                  #93a1a1

selection_background    #81908f
selection_foreground    #002831

color0                  #1c353c
color1                  #8a3630
color2                  #5e6a00
color3                  #776301
color4                  #346289
color5                  #86375f
color6                  #336e69
color7                  #959289
color8                  #192e35
color9                  #82431f
color10                 #485358
color11                 #505a5f
color12                 #5f6768
color13                 #545582

# macOS
macos_traditional_fullscreen yes
hide_window_decorations titlebar-only
