#! /bin/sh

#  ██                                            
# ░██              ██████                        
# ░██       ██████░██░░░██ ███     ██ ██████████ 
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░
#                 github.com/rxtsel               

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d     
        
bspc config border_width         2
bspc config border_normal_color  '#1d1d1d'
bspc config focus_follows_pointer	true 
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config border_radius 	 0
bspc config single_monocle true
bspc config borderless_monocle true

######## CUSTOM ##########
xsetroot -cursor_name left_ptr &

######## TOOLS ##########
polybar &
nm-applet &
picom &
redshift &
dunst &
xfce4-power-manager &

####### LOCK SCREEN #######
pkill xautolock
xautolock -time 5 -locker "betterlockscreen -l" -notify 30 -notifier "notify-send 'Locker' 'Locking screen in 30 seconds'" -killtime 5 -killer "systemctl suspend" &

####### WALLPAPERS #######
feh --bg-scale /home/rxtsel/Pictures/Nordic.png &
