#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


if xrandr | grep -q "HDMI-1 connected"; then
  bspc monitor HDMI-1 -d I II III IV V VI

else
  bspc monitor -d I II III IV V VI
fi

bspc config border_width         1

# gap=15
# height=0
# bspc config window_gap $gap;
# bspc config top_padding $(($height-gap))
# bspc config left_padding -$gap
# bspc config right_padding -$gap
# bspc config bottom_padding -$gap

##Color settings
bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 0.05
bspc config focused_border_color "#000000"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Thunderbird desktop='^6'

# bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true
bspc config auto_alternate          true

# mouse
# bspc config -m focused pointer_follows_monitor true

####### LAUNCHERS #######
polybar &
picom &
# nm-applet &
blueman-applet &
xfce4-power-manager &
birdtray &

###### DUAL MONITOR ######
if xrandr | grep "HDMI-1 connected"; then
    # xrandr --output HDMI-1 --primary --mode 1920x1080 --rate 120 --output eDP-1 --auto --left-of HDMI-1 &
    xrandr --output HDMI-1 --primary --mode 1920x1080 --rate 120 --output eDP-1 --off
fi

####### WALLPAPERS #######
feh --bg-scale /home/rxtsel/wallpapers/green.jpg &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
